### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by shepardac** [ElevenPaths/Airdrop-Crazy#2]
hello I have installed as described on your github page (including troubleshooting steps), but continue to get this error:

 File "adv_wifi.py", line 4, in <module>
    from core.adv_wifi import AdvWifi
  File "/home/user/Airdrop-Crazy/airdrop_crazy/core/adv_wifi.py", line 9, in <module>
    from utils.bluetooth_utils import (toggle_device, start_le_advertising, stop_le_advertising)
ModuleNotFoundError: No module named 'utils.bluetooth_utils'

sudo python3 ble_read_state.py -h
Traceback (most recent call last):
  File "ble_read_state.py", line 4, in <module>
    from core.ble_read_state import Ble_Read
  File "/home/user/Airdrop-Crazy/airdrop_crazy/core/ble_read_state.py", line 4, in <module>
    from utils.ble_apple.ble_utils import Ble_Apple_Utils
ModuleNotFoundError: No module named 'utils.ble_apple'

any help would be greatly appreciated

**Comment by carb00191** [comment]
> hello I have installed as described on your github page (including troubleshooting steps), but continue to get this error:
> 
> File "adv_wifi.py", line 4, in
> from core.adv_wifi import AdvWifi
> File "/home/user/Airdrop-Crazy/airdrop_crazy/core/adv_wifi.py", line 9, in
> from utils.bluetooth_utils import (toggle_device, start_le_advertising, stop_le_advertising)
> ModuleNotFoundError: No module named 'utils.bluetooth_utils'
> 
> sudo python3 ble_read_state.py -h
> Traceback (most recent call last):
> File "ble_read_state.py", line 4, in
> from core.ble_read_state import Ble_Read
> File "/home/user/Airdrop-Crazy/airdrop_crazy/core/ble_read_state.py", line 4, in
> from utils.ble_apple.ble_utils import Ble_Apple_Utils
> ModuleNotFoundError: No module named 'utils.ble_apple'
> 
> any help would be greatly appreciated

Run the 

https://github.com/ElevenPaths/Airdrop-Crazy#troubleshooting
